import pandas as pd
from typing import List, Dict
from src.strategies.base import StrategyBase, StrategyRegistry
from src.signals.models import Signal, SignalSide

@StrategyRegistry.register("MovingAverageCrossover")
class MovingAverageCrossover(StrategyBase):
    """
    A sample strategy that generates BUY signals when a short-term moving average
    crosses above a long-term moving average.
    """
    def __init__(self, name: str, short_window: int = 5, long_window: int = 20, tickers: List[str] = None, **kwargs):
        super().__init__(name, tickers=tickers, **kwargs)
        self.short_window = short_window
        self.long_window = long_window

    def generate_signals(self, market_data: Dict[str, pd.DataFrame], fundamental_data: pd.DataFrame = None) -> List[Signal]:
        """
        Generate signals for each ticker based on the Moving Average crossover logic.
        
        Args:
            market_data: Dictionary mapping ticker symbols to their DataFrames.
            fundamental_data: Optional fundamental data (not used here).
            
        Returns:
            List[Signal]: Standards signals generated by the strategy.
        """
        signals = []
        for ticker, df in market_data.items():
            if len(df) < self.long_window:
                continue

            # Calculate Moving Averages
            short_ma = df['close'].rolling(window=self.short_window).mean()
            long_ma = df['close'].rolling(window=self.long_window).mean()

            # Identify signal (Simplified logic: check only the last row)
            if short_ma.iloc[-1] > long_ma.iloc[-1] and short_ma.iloc[-2] <= long_ma.iloc[-2]:
                side = SignalSide.BUY
            elif short_ma.iloc[-1] < long_ma.iloc[-1] and short_ma.iloc[-2] >= long_ma.iloc[-2]:
                side = SignalSide.SELL
            else:
                side = SignalSide.HOLD

            # Create Signal object
            signals.append(Signal(
                symbol=ticker,
                side=side,
                strength=1.0,
                confidence=0.8,
                strategy_name=self.name,
                metadata={
                    "short_ma": short_ma.iloc[-1],
                    "long_ma": long_ma.iloc[-1]
                }
            ))
            
        return signals

